export const DOCTORS = [
  {
    name: "Dr. Kumar Saket",
    photo: "/Dr Saket.png",
    hindi: "रेटिना विशेषज्ञ",
    englishFocus: "Medical Retina Specialist",
    label: "M.B.B.S., D.N.B. | Medical Retina Specialist",
    qual: "M.B.B.S., D.N.B.",
    spec: "Medical Retina Specialist",
    role: "Ex. HOD Medical Retina Services, Purnima Netralaya",
    bio: "Dr. Kumar Saket is an experienced ophthalmologist and Medical Retina Specialist with over 12 years of experience in ophthalmology. He is dedicated to providing comprehensive, compassionate, and evidence-based eye care, with particular expertise in medical retina, cataract care, and ocular trauma.",
    extraBio: [
      "Dr. Kumar Saket completed his M.B.B.S. from K.M.C.H., Bihar, followed by D.N.B. in Ophthalmology from Susrut Eye Foundation and Research Centre, Kolkata. His clinical experience has enabled him to develop a focused approach to the diagnosis and management of a wide range of eye conditions.",
      "Dr. Kumar Saket also provides comprehensive evaluation and treatment for cataract and a range of common medical eye conditions. Each patient's treatment plan is developed according to their individual eye health, visual requirements, and overall medical history.",
      "Whether you require a routine eye examination, cataract evaluation, retinal assessment, diabetic eye screening, or treatment for an eye injury, Dr. Kumar Saket and the team at MEERA GAYATRI EYE FOUNDATION are committed to helping you protect your vision and maintain healthy eyes.",
    ],
    quote:
      "Good eye care begins with listening, accurate diagnosis, and helping patients make informed decisions about their vision.",
    bookLabel: "Book an Appointment",
    stats: [
      { value: "12+", label: "Years in ophthalmology" },
      { value: "D.N.B.", label: "Ophthalmology" },
    ],
    expertise: [
      "Medical Retina",
      "Diabetic Retinopathy",
      "Retinal Disorders",
      "Cataract",
      "Ocular Trauma",
      "Glaucoma",
      "Dry Eye and Ocular Surface Disorders",
      "Comprehensive Ophthalmic Care",
    ],
    memberships: [
      "Life Member – AIOS",
      "Life Member – DOS",
      "Life Member – OSWB",
      "Life Member – JOS, JHOS",
    ],
    treats: [
      {
        title: "Cataract",
        plain: "Cloudy eye. New clear lens.",
        image: "/treats/saket-cataract.png",
      },
      {
        title: "Retina",
        plain: "Back of the eye. Injection or laser.",
        image: "/treats/saket-retina.png",
      },
      {
        title: "Laser care",
        plain: "A laser is used when the eye needs it.",
        image: "/treats/saket-laser.png",
      },
      {
        title: "Glaucoma",
        plain: "High eye pressure. We bring it down.",
        image: "/treats/saket-glaucoma.png",
      },
    ],
    highlights: [
      "Ex. HOD Medical Retina Services, Purnima Netralaya",
      "Ex. Visiting Consultant, K.G.M.H, Medica, Bistupur",
      "Ex. Visiting Consultant, Jamshedpur Eye Hospital, Sakchi",
    ],
  },
  {
    name: "Dr. Malay Kumar Dwivedi",
    photo: "/Dr Malay Kumar Dwiwedi.jpg",
    hindi: "शिशु नेत्र रोग विशेषज्ञ",
    englishFocus: "Paediatric Ophthalmologist",
    label: "M.B.B.S., M.S., F.P.O.A.S. | Paediatric Ophthalmologist",
    qual: "M.B.B.S., M.S., F.P.O.A.S.",
    spec: "Paediatric Ophthalmologist",
    role: "Ex Fellow, Aravind Eye Hospital, Madurai",
    bio: "Dr. Malay Kumar Dwivedi is a dedicated ophthalmologist with specialized training in Paediatric Ophthalmology, providing comprehensive eye care for infants, children, and adolescents. With a compassionate and child-friendly approach, Dr. Dwivedi focuses on the early detection, diagnosis, and management of eye and vision problems during the crucial years of visual development.",
    extraBio: [
      "Every child deserves the opportunity to develop clear and healthy vision.",
      "At MEERA GAYATRI EYE FOUNDATION, Dr. Malay Kumar Dwivedi is committed to providing specialized paediatric eye care with expertise, compassion, and a focus on each child's long-term visual development.",
    ],
    quote: "",
    bookLabel: "Book a Paediatric Eye Consultation",
    stats: [
      { value: "F.P.O.A.S.", label: "Paediatric fellowship" },
      { value: "Aravind", label: "Madurai" },
    ],
    expertise: [
      "Squint / Strabismus",
      "Lazy Eye / Amblyopia",
      "Childhood refractive errors",
      "Paediatric cataract",
      "Congenital eye disorders",
      "Ptosis and eyelid disorders",
      "Blocked tear ducts",
      "Childhood eye infections and allergies",
      "Abnormal eye movements",
      "Vision problems affecting learning and school performance",
      "Other developmental and paediatric eye conditions",
    ],
    memberships: [
      "M.B.B.S.",
      "M.S. – Ophthalmology",
      "Long Term Fellowship in Paediatric Ophthalmology and Adult Strabismus from Aravind Eye Hospital, Madurai",
      "Life membership of AIOS, DOS, EIZOC, ACOIN, JHOS, JOS",
    ],
    treats: [
      {
        title: "Cataract",
        plain: "Cloudy eye. New clear lens.",
        image: "/treats/malay-cataract.png",
      },
      {
        title: "Child eyes",
        plain: "We check if a child sees well.",
        image: "/treats/malay-child.png",
      },
      {
        title: "Squint",
        plain: "We can straighten the eye.",
        image: "/treats/malay-squint.png",
      },
      {
        title: "Eye injury",
        plain: "Hurt eye. We treat it here.",
        image: "/treats/malay-injury.png",
      },
    ],
    highlights: [
      "Ex Fellow, Aravind Eye Hospital, Madurai",
      "Ex. Consultant, Purnima Netralaya, Tamolia",
      "Ex. Visiting Consultant, K.G.M.H, Medica, Bistupur",
      "Ex. Visiting Consultant, Jamshedpur Eye Hospital, Sakchi",
    ],
  },
] as const;
